version: 1.1

app:
  env: development
  mode: debug
  port: 8081
  trackerDomain: track.example.com
  stats:
    enabled: true
    path: /stats
  timeout:
    enabled: false
    ms: 2000
  rateLimiter:
    enabled: false
    period: S
    limit: 10

snowplow:
  enabled: true
  standardRoutesEnabled: false
  openRedirectsEnabled: false
  getPath: /plw/g
  postPath: /plw/p
  redirectPath: /plw/r
  anonymize:
    ip: true
    userId: true

cloudevents:
  enabled: true
  postPath: /ce/p
  batchPostPath: /ce/bp

generic:
  enabled: true
  postPath: /gen/p
  batchPostPath: /gen/bp
  contexts:
    rootKey: contexts
    schemaKey: schema
    dataKey: payload
  payload:
    rootKey: payload
    schemaKey: schema
    dataKey: data

cookie:
  enabled: true
  name: nuid
  secure: false
  ttlDays: 365
  domain: example.com
  path: /
  sameSite: Lax

cors:
  allowOrigin:
    - "*"
  allowCredentials: true
  allowMethods:
    - POST
    - OPTIONS
    - GET
  maxAge: 86400

schemaCache:
  schemaCacheBackend:
    type: fs
    path: schemas
  ttlSeconds: 300
  maxSizeBytes: 104857600 # 100mb -> 100 * 1024 * 1024
  purge:
    enabled: true
    path: /c/purge
  schemaEndpoints:
    enabled: true

sink:
  type: stdout
  produceTimeout: 3

tele:
  enabled: true
  heartbeatMs: 30000
