version: 1

app:
  env: dev
  mode: release
  port: 8081
  trackerDomain: honeypot.silverton.io
  stats:
    enabled: true
    path: /stats
  timeout:
    enabled: false
    ms: 10000

snowplow: # Snowplow events
  enabled: true
  standardRoutesEnabled: true
  openRedirectsEnabled: true
  getPath: /plw/g
  postPath: /plw/p
  redirectPath: /plw/r
  anonymize:
    ip: false
    userId: false

generic: # Generic self describing events
  enabled: true
  postPath: /gen/p
  batchPostPath: /gen/bp
  contexts:
    rootKey: contexts
    schemaKey: schema
    dataKey: payload
  event:
    rootKey: payload
    schemaKey: schema
    dataKey: payload

cloudevents: # Cloudevents
  enabled: true
  postPath: /ce/p
  batchPostPath: /ce/bp

cookie:
  name: sp-nuid
  secure: False
  ttlDays: 365
  domain: silverton.io
  path: /
  sameSite: Lax

cors:
  allowOrigin:
    - "*"
  allowCredentials: true
  allowMethods:
    - POST
    - OPTIONS
    - GET
  maxAge: 86400

schemaCache:
  schemaCacheBackend:
    type: gcs
    bucket: BUCKET_NAME
    path: /
  ttlSeconds: 300
  maxSizeBytes: 104857600 # 100mb -> 100 * 1024 * 1024
  purge:
    enabled: true
    path: /c/purge

sink:
  type: stdout
  validEventTopic: VALID_EVENT_TOPIC_NAME
  invalidEventTopic: INVALID_EVENT_TOPIC_NAME
  produceTimeout: 3

tele:
  enabled: true
